### ISSUE TITLE
FIGMA BLOG ISSUE (initial prototype)

### ISSUE THREAD

**Issue by ssg8288** [Clinify-Open-Sauce/ClinifyBlog#2]
Dear Repo Maintainer,

In the below image (taken from the hyperlink of the Figma blog design )

![image](https://user-images.githubusercontent.com/43617730/120183532-72c8a100-c22d-11eb-967c-9cd237c5cf6c.png)

- kindly look at the two tiles there the width alignment is not proper some fine adjustments are required kindly, correct them

**Comment by ManavSaspal** [comment]
corrected, thanks.
